---
- name: add block of content to a file
  hosts: all
  become: true

  tasks:
    - name: add block text to an exsiting file
      ansible.builtin.blockinfile:
        path: "/home/{{ ansible_facts.env.SUDO_USER }}/users.txt"
        block: |
          this block of text contsists of two lines
          They has been add by the  blockinfile module
        state: present
